name: blog
channels:
- conda-forge
- defaults
dependencies:
- blinker=1.4=py35_0
- feedgenerator=1.9=py35_0
- ghp-import=0.4.1=py35_0
- anaconda-client=1.6.0=py35_0
- clyent=1.2.2=py35_0
- docutils=0.12=py35_2
- html5lib=0.999=py35_0
- jinja2=2.8.1=py35_0
- markdown=2.6.7=py35_0
- markupsafe=0.23=py35_2
- openssl=1.0.2j=0
- pip=9.0.1=py35_1
- pygments=2.1.3=py35_0
- python=3.5.2=0
- python-dateutil=2.6.0=py35_0
- pytz=2016.10=py35_0
- pyyaml=3.12=py35_0
- readline=6.2=2
- requests=2.12.4=py35_0
- setuptools=27.2.0=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- unidecode=0.04.19=py35_0
- wheel=0.29.0=py35_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - pelican==3.6.3
