name: blog
channels:
  - defaults
dependencies:
  - beautifulsoup4=4.6.3
  - ca-certificates=2018.03.07
  - certifi=2018.11.29
  - libedit=3.1.20170329
  - libffi=3.2.1
  - markdown=3.0.1
  - ncurses=6.1
  - openssl=1.1.1a
  - pip=18.1
  - pygments=2.3.1
  - python=3.6.7
  - readline=7.0
  - setuptools=40.6.3
  - sqlite=3.26.0
  - tk=8.6.8
  - wheel=0.32.3
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - blinker==1.4
    - docutils==0.14
    - feedgenerator==1.9
    - html5lib==1.0.1
    - jinja2==2.10
    - markupsafe==1.1.0
    - pelican==4.0.1
    - python-dateutil==2.7.5
    - pytz==2018.7
    - six==1.12.0
    - smartypants==2.0.1
    - typogrify==2.0.7
    - unidecode==1.0.23
    - webencodings==0.5.1

