name: blog
channels:
- defaults
dependencies:
- beautifulsoup4=4.5.1=py35_0
- markdown=2.6.6=py35_0
- pip=8.1.2=py35_0
- pygments=2.1.3=py35_0
- python=3.5.2=0
- setuptools=25.1.6=py35_0
- vs2015_runtime=14.0.25123=0
- wheel=0.29.0=py35_0
- pip:
  - blinker==1.4
  - docutils==0.13.1
  - feedgenerator==1.9
  - html5lib==0.999999999
  - jinja2==2.9.3
  - markupsafe==0.23
  - pelican==3.6.3
  - python-dateutil==2.6.0
  - pytz==2016.10
  - six==1.10.0
  - smartypants==1.8.6
  - typogrify==2.0.7
  - unidecode==0.4.20
  - webencodings==0.5

